### PR TITLE
fix: unnecessary uniqueness check for idShort

### LINKED ISSUE #528: Remove duplicate check for idShorts in submodel level
### Current Behavior
Duplicate check for idShorts exists in submodel level

### Expected Behavior
Remove duplicate check for idShorts in submodel level

### Steps To Reproduce
Creates a new Submodel Descriptor using POST /shell-descriptors/{aasIdentifier}/submodel-descriptors 
Or
Updates an existing Submodel Descriptor using PUT /shell-descriptors/{aasIdentifier}/submodel-descriptors/{submodelIdentifier}

### PR DESCRIPTION
**Pull request by vasil-tenev**
## Description
Fixes #528 by removing unnecessary uniqueness check for idShort

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

File: backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java [hunk 1]
```diff
@@ -420,15 +419,6 @@ public Submodel save( String externalShellId, Submodel submodel, String external
...
       submodel.setShellId( shellFromDb );
 
-      //uniqueness on shellId and idShort
-      boolean isIdShortPresent = Optional.of( shellFromDb ).map( Shell::getSubmodels ).stream().flatMap( Collection::stream )
-            .map( Submodel::getIdShort )
-            .anyMatch(
-                  idShort -> idShort.equalsIgnoreCase( submodel.getIdShort() ) ); // check whether the input sub-model.idShort exists in DB
-
-      if ( isIdShortPresent ) {// Throw exception if sub-model.idShort exists in DB
-         throw new DuplicateKeyException( DUPLICATE_SUBMODEL_ID_SHORT_EXCEPTION );
```
Comment (shijinrajbosch) [inline backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java:430]: Could you please also remove DUPLICATE_SUBMODEL_ID_SHORT_EXCEPTION constant, as it is no longer in use?

File: backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java [hunk 2]
```diff
@@ -27,7 +27,6 @@
 import java.time.ZoneOffset;
```
Comment (shijinrajbosch) [inline backend/src/main/java/org/eclipse/tractusx/semantics/registry/service/ShellService.java:27]: Could you please update the CHANGELOG.md to reflect the changes ?

File: CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,12 @@ All notable changes to this project will be documented in this file.
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
+## [Unreleased]
```
Comment (shijinrajbosch) [inline CHANGELOG.md:7]: please correct the version

File: backend/src/test/resources/integrationtests/aas-registry-usecases/16_testCreateSubmodelWithExistingIdExpectSuccess/1_post_shell/expected-response.json [hunk 4]
```diff
@@ -1,61 +1,61 @@
-{
```
Comment (shijinrajbosch) [inline backend/src/test/resources/integrationtests/aas-registry-usecases/16_testCreateSubmodelWithExistingIdExpectSuccess/1_post_shell/expected-response.json:1]: Could you please help me understand the changes made here, as GitHub shows some deletions and additions? If there are no functional changes, can we correct the code style or spacing issues to keep the commit clean?

File: backend/src/test/resources/integrationtests/aas-registry-usecases/16_testCreateSubmodelWithExistingIdExpectSuccess/1_post_shell/request.json [hunk 5]
```diff
@@ -1,61 +1,61 @@
-{
```
Comment (shijinrajbosch) [inline backend/src/test/resources/integrationtests/aas-registry-usecases/16_testCreateSubmodelWithExistingIdExpectSuccess/1_post_shell/request.json:1]: Could you please help me understand the changes made here, as GitHub shows some deletions and additions? If there are no functional changes, can we correct the code style or spacing issues to keep the commit clean?
